In [1]:
import os,sys,glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
script_dir = os.path.abspath('') #only in jupyter demo, different in .py
parent_dir = os.path.join(os.path.dirname(script_dir), '')
sys.path.append(parent_dir) #only in jupyter demo, different in .py
from utils import util
from tqdm import tqdm
import joblib


In [47]:
### say we want to predict binding likelihood of CA
model_CA = joblib.load(f'{parent_dir}/weight3/one_class_svm_CA_nu_0.1_roc_0.72.pkl')
model_CA = joblib.load(f'{parent_dir}/weight4/svm_svc_CA_roc_0.81.pkl')
model_ZN  = joblib.load(f'{parent_dir}/weight3/one_class_svm_ZN_nu_0.0447_roc_0.794.pkl')
model_ZN = joblib.load(f'{parent_dir}/weight4/svm_svc_ZN_roc_0.873.pkl')

In [48]:
test_pdb = '/home/lhtran/class/scaffold_squad/test_cases/test_CA_1.pdb'
pdb_data = util.preprocess_tip_atom(test_pdb, metal='CA',metal_id=9)#, metal_id=15859)
pdb_data = pdb_data.reshape(1, -1)

In [49]:
model_CA.predict(pdb_data)

array([1.])

In [50]:
# tmp = np.array([  1.        ,   1.        ,   1.        ,   1.        ,
#          0.        ,   0.        ,   0.        ,   0.        ,
#          2.35129929,   2.40874028,   2.59298944,   2.70946288,
#          0.        ,   0.        ,   0.        ,   0.        ,
#        152.        , 152.        , 152.        , 152.        ,
#          0.        ,   0.        ,   0.        ,   0.        ,
#          3.44      ,   3.44      ,   3.44      ,   3.44      ,
#          0.        ,   0.        ,   0.        ,   0.        ,
#          4.        ,   4.        ,   4.        ,   4.        ,
#          0.        ,   0.        ,   0.        ,   0.        ,
#          6.        ,   6.        ,   6.        ,   6.        ,
#          0.        ,   0.        ,   0.        ,   0.        ])

In [41]:
tmp = tmp.reshape(1, -1)

In [42]:
test_pdb = '/home/lhtran/class/scaffold_squad/test_cases/test_ZN_1.pdb'
pdb_data = util.preprocess_tip_atom(test_pdb, metal='ZN',metal_id=1)#, metal_id=15859)
pdb_data = np.reshape(pdb_data, (1, -1))

In [43]:
model_ZN.predict(pdb_data)

array([-1])

In [39]:
pdb_data

array([[  1.        ,   1.        ,   1.        ,   1.        ,
          1.        ,   1.        ,   0.        ,   0.        ,
          3.2110846 ,   2.85012937,   2.90439034,   2.849967  ,
          3.21100187,   2.90426397,   0.        ,   0.        ,
        170.        , 152.        , 152.        , 152.        ,
        170.        , 152.        ,   0.        ,   0.        ,
          2.55      ,   3.44      ,   3.44      ,   3.44      ,
          2.55      ,   3.44      ,   0.        ,   0.        ,
          0.        ,   4.        ,   4.        ,   4.        ,
          0.        ,   4.        ,   0.        ,   0.        ,
          4.        ,   6.        ,   6.        ,   6.        ,
          4.        ,   6.        ,   0.        ,   0.        ]])